"""Render implement prompt and PR body from selected task."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from paths import find_repo_root, load_config, load_json, out_dir, write_text


def _checklist(items: list[str]) -> str:
    return "\n".join(f"- [ ] {c}" for c in items)


def render_implement_prompt(template: str, task: dict[str, Any]) -> str:
    task_json = json.dumps(task, indent=2, ensure_ascii=False)
    text = template.replace("{{TASK_JSON}}", task_json)
    text = text.replace("{{TASK_ID}}", str(task.get("id") or "TASK"))
    return text


def render_pr_body(template: str, task: dict[str, Any], graph_commit: str | None) -> str:
    text = template
    replacements = {
        "{{TASK_ID}}": str(task.get("id") or ""),
        "{{PRIORITY}}": str(task.get("priority") or ""),
        "{{GRAPH_COMMIT}}": graph_commit or "unknown",
        "{{PROBLEM}}": str(task.get("problem") or ""),
        "{{SOLUTION}}": str(task.get("solution") or ""),
        "{{ACCEPTANCE_CHECKLIST}}": _checklist(list(task.get("acceptance_criteria") or [])),
        "{{RISK}}": str(task.get("estimated_risk") or "medium"),
        "{{AGENT_NOTES}}": "Generated by agentic pipeline (scripts/agentic).",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text


def run(repo_root: Path | None = None) -> dict[str, str]:
    root = repo_root or find_repo_root()
    config = load_config(root)
    out = out_dir(root, config)
    selected_path = out / config["outputs"]["selected_task"]
    if not selected_path.is_file():
        raise FileNotFoundError(
            f"Missing {selected_path}; run: python scripts/agentic/cli.py plan"
        )
    task = load_json(selected_path)
    plan_path = out / config["outputs"]["plan"]
    graph_commit = None
    if plan_path.is_file():
        graph_commit = load_json(plan_path).get("graph_commit")

    impl_tmpl = (root / ".agentic" / "prompts" / "implement.md").read_text(encoding="utf-8")
    pr_tmpl = (root / ".agentic" / "prompts" / "pr-body.md").read_text(encoding="utf-8")

    implement_md = render_implement_prompt(impl_tmpl, task)
    pr_body = render_pr_body(pr_tmpl, task, graph_commit)

    write_text(out / config["outputs"]["implement_prompt"], implement_md)
    write_text(out / "pr-body.md", pr_body)

    policies = (root / ".agentic" / "policies.json").read_text(encoding="utf-8")
    write_text(
        out / "agent-context.md",
        "\n\n".join(
            [
                "# Agent context bundle",
                "## Policies",
                "```json",
                policies,
                "```",
                "## Selected task",
                "```json",
                json.dumps(task, indent=2, ensure_ascii=False),
                "```",
                "## Implementation prompt",
                implement_md,
            ]
        ),
    )
    return {
        "implement_prompt": str(out / config["outputs"]["implement_prompt"]),
        "pr_body": str(out / "pr-body.md"),
        "agent_context": str(out / "agent-context.md"),
    }


if __name__ == "__main__":
    paths = run()
    for k, v in paths.items():
        print(f"{k}: {v}")
